version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: pratadaniel94/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - develop-network
    depends_on:
      - "node1"
      - "node2"
      - "node3"
  node1:
    build:
      dockerfile: ./docker/app.dockerfile
      context: .
      image: pratadaniel94/website
      container_name: application1
      ports:
        - "8000"
      networks:
        - develop-network
  node2:
    build:
      dockerfile: ./docker/app.dockerfile
      context: .
      image: pratadaniel94/website
      container_name: application2
      ports:
        - "8000"
      networks:
        - develop-network

  node3:
    build:
      dockerfile: ./docker/app.dockerfile
      context: .
      image: pratadaniel94/website
      container_name: application3
      ports:
        - "8000"
      networks:
        - develop-network
networks:
  - develop-network:
      driver: bridge
